config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :products do
    resources :photos, only: [:create,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploaders :images, PhotoUploader
  serialize :images, JSON # If you use SQLite, add this line.
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :photo, dependent: :destroy

  accepts_nested_attributes_for :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_product, only:[:create,:destroy]
  def create
    add_more_images(photo_params[:images])
    flash[:error] = "Failed uploading images" unless @product.save
    redirect_to :back
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = "Failed deleting image" unless @product.save
    redirect_to :back
  end

  private

  def find_product
    @product = Product.find(params[:product_id])
  end

  def photo_params
    if params.dig(:photo,:images)
      params[:photo][:images] = params[:photo][:images].values
    end
    params.require(:photo).permit({ images:[] })
  end

  def remove_image_at_index(index)
    remain_images = @product.photo.images # copy the array
    deleted_image = remain_images.delete_at(index) # delete the target image
    deleted_image.try(:remove!) # delete image from S3
    @product.photo.images = remain_images # re-assign back

    if remain_images.length == 0
      @product.photo.remove_images = true
    end
  end

  def add_more_images(new_images)
    images = @product.photo.images
    images += new_images
    @product.photo.images = images
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
    @photo = @product.photo
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private
  def product_params
    if params.dig(:product,:photo_attributes,:images)
      params[:product][:photo_attributes][:images] = params[:product][:photo_attributes][:images].values
    end
    params.require(:product).permit(:name,photo_attributes:[:id,{ images:[] }])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultipeImagesUploadWithCarrierwaveAndDropzone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= simple_form_for @product do  |f| %>
  <%= f.input :name %>
  <div id="myDorpzone" class="dropzone">
    <%= f.simple_fields_for :photo do |c| %>
      <div class="fallback">
        <%= c.input :images , as: :file,  input_html: { multiple: 'multiple'} %>
      </div>
    <% end %>
  </div>
  <br>
  <%= f.submit "Submit",class:"btn btn-info"%>
<% end %>

<script type="text/javascript">
  $(function(){
      var post_url = "/products/"+<%= @product.id %>+"/photos";
      var myDropzone = new Dropzone("#myDorpzone", {
        url: post_url,
        method: "POST",
        paramName: "photo[images]",
        uploadMultiple: true,
        autoProcessQueue: false,
        addRemoveLinks: true,
        parallelUploads: 100,
        maxFiles: 100,
        removedfile: function(file){
          var _ref,
              product_id = file.product_id,
              image_index = file.index,
              url = "/products/" + product_id + "/photos/" + image_index;
          $.ajax({
              type: 'DELETE',
              url: url
          });
          return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
        },
        headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
        init: function() {
          var myDropzone = this;
          $("input[type='submit']").on("click", function(e) {
              if (myDropzone.getQueuedFiles().length > 0) {
                  e.preventDefault();
                  e.stopPropagation();
                  myDropzone.processQueue();
                  return;
              }
          });
          this.on("successmultiple", function(files, response) {
            window.location.href = '<%= products_path %>'
          });
        }
      });
      <% @product.photo.images.each_with_index do |image, index| %>
        var mockFile = {
          name: "<%= image.file.filename %>",
          size: <%= image.size %>,
          index: <%= index %>,
          product_id : <%= @product.id %>
        }
        myDropzone.emit("addedfile", mockFile);
        myDropzone.createThumbnailFromUrl(mockFile, "<%= image.url %>");
        myDropzone.emit("complete", mockFile);
        myDropzone.files.push(mockFile);
      <% end %>
    });
</script>

app/views/products/index.html.erb
<h2>Product List</h2>
<%= link_to("New Product", new_product_path,class:"btn btn-info pull-right") %>
<table class="table table-bordered">
  <thead>
    <th>#</th>
    <th>Name</th>
    <th>Images</th>
    <th>Action</th>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td>
        <% product.photo.images.each do |image| %>
          <%= image_tag(image.thumb.url,class:"thumbnail") %>
        <% end %>
      </td>
      <td>
        <%= link_to("Edit", edit_product_path(product),class: "btn btn-success") %>
        <%= link_to("Delete", product_path(product),method: :delete, data:{confirm: "Are you sure ?"},class: "btn btn-danger") %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h2>New Product</h2>
<%= simple_form_for @product do  |f| %>
  <%= f.input :name %>
  <div id="myDropzone" class="dropzone">
    <%= f.simple_fields_for :photo do |c| %>
      <div class="fallback">
        <%= c.input :images , as: :file,  input_html: { multiple: 'multiple'} %>
      </div>
    <% end %>
  </div>
  <%= f.submit "Submit",class:"btn btn-info" %>
<% end %>
<script type="text/javascript">
  $(function(){
      var myDropzone = new Dropzone("#myDropzone", {
        url: "/products",
        paramName: "product[photo_attributes][images]",
        uploadMultiple: true,
        addRemoveLinks: true,
        autoProcessQueue: false,
        parallelUploads: 100,
        maxFiles: 100,
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        init: function() {
          var myDropzone = this;
          $("input[type='submit']").on("click", function(e) {
              if (myDropzone.getQueuedFiles().length > 0){
                e.preventDefault();
                e.stopPropagation();
                myDropzone.processQueue();
                return;
              }
          });
          this.on("sendingmultiple", function(data, xhr, formData) {
            formData.append("product[name]",$('#product_name').val());
          });
          this.on("successmultiple", function(files, response) {
            window.location.href = '<%= products_path %>'
          });
        }
      });

    });
</script>